server:
  port: 8083

spring:
  application:
    name: scan-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:vulnplatform}
    username: ${POSTGRES_USER:vuln}
    password: ${POSTGRES_PASSWORD:vuln_secret_change_me}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
  task:
    execution:
      pool:
        core-size: 4
        max-size: 8
        queue-capacity: 100
        thread-name-prefix: scan-exec-

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  vulnerability-service:
    url: ${VULNERABILITY_SERVICE_URL:http://vulnerability-service:8084}
  alert-service:
    url: ${ALERT_SERVICE_URL:http://alert-service:8085}
